name: Callee
on:
  workflow_call:
    inputs:
      stage:
        type: string
        description: The stage
        required: true
  workflow_dispatch:
    inputs:
      stage:
        type: string
        description: The stage
        required: false
        default: ''

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - run: jq < ${{ github.event_path }}

  pushed:
    if: github.event_name == 'pushed'
    runs-on: ubuntu-latest
    steps:
      - run: echo "Pushed!"

  called-for-prod:
    if: inputs.stage == 'prod'
    runs-on: ubuntu-latest
    steps:
      - run: echo "Called for prod!"
