on:
  deployment:
  workflow_dispatch:
    inputs:
      new-tag:
        required: false
        default: 'v2.3.4'
        type: string


jobs:
  job-a:
    runs-on: ubuntu-latest
    steps:
      run: |
        if [ "${{ github.event_name}}" == "workflow_dispatch" ]
        then
          echo "name=${{ inputs.new-tag }}" >> "$GITHUB_OUTPUT"
        fi
        if [ "${{ github.event_name}}" == "deployment" ]
        then
          REF="$GITHUB_REF"
          TAG_NAME=${REF#"refs/tags/"}
          echo "name=$TAG_NAME" >> "$GITHUB_OUTPUT"
        fi
      id: tag
    outputs:
      new-tag-name: ${{ steps.tag.outputs.name }}

  job-b:
    runs-on: ubuntu-latest
    needs: job-a
    steps:
      - run: echo ${{ needs.job-a.outputs.new-tag-name }}
