on:
  push:
    branches:
      - main


jobs:
  greet:
    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        stage: [ dev, int, qs, prod ]
    steps:
      - name: Say Hello
        run: |
          echo "Secret: ${{ secrets['GREETING-dev'] }}"
          echo "Secret: ${{ secrets['GREETING-int'] }}"
          echo "Secret: ${{ secrets['GREETING-qs'] }}"
          echo "Secret: ${{ secrets['GREETING-prod'] }}"
