on:
  push:
    branches:
      - main


jobs:
  greet:
    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        stage: [ dev, int, qs, prod ]
    environment: dev
    steps:
      - name: Say Hello
        run: |
          echo "Secret: ${{ secrets['GREETING'] }}"
          echo "Secret: ${{ secrets.GREETING }}"
