name: SemVer input validation

on:
  workflow_dispatch:
jobs:
  pre-checks:
    permissions:
      actions: read
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [ 'dev', 'testing', 'int', 'qs', 'prod' ]
        tag: [ 'latest', 'v1.4.0' ]
    steps:
      - name: Check input tag
        id: tag-check
        shell: python
        # language=python
        run: |
          import os
          import re
          
          tag = "${{ matrix.tag }}"
          environment = "${{ matrix.environment }}"
          # Basic regex to match SemVer tags starting with 'v' followed by major, minor,
          # and patch versions, with an optional arbitrary qualifier at the end.
          semver_pattern = "v(\\d+\\.?){3}(-.+)?"
          is_semantic_version = re.match(semver_pattern, tag)

          if not ((environment == 'dev' or environment == 'testing') or is_semantic_version):
              print(f'::warning title=Invalid deployment tag::In the future a deployment into {environment} using {tag} will be rejected.')
