name: SemVer input validation

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment'
        required: true
        type: choice
        options:
          - "dev"
          - "testing"
          - "int"
          - "qs"
          - "prod"
      tag:
        description: 'image tag for deployment'
        required: false
        type: string
        default: 'latest'

jobs:
  pre-checks:
    environment:
      name: ${{ inputs.environment }}
      url: ${{ vars.app_host }}
    permissions:
      actions: read
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: ['dev', 'testing', 'int', 'qs', 'prod']
        tag: ['latest', 'v1.4.0']
    steps:
      - name: Check input tag
        uses: paulschuberth/regex-extract-action@v2
        id: tag-check
        with:
          haystack: ${{ matrix.tag }}
          # Basic regex to match SemVer tags starting with 'v' followed by major, minor,
          # and patch versions, with an optional arbitrary qualifier at the end.
          needle: 'v(\d+\.?){3}(-.+)?'

      # On stages int, qs, and prod we require the tag to be a semantic version
      # On stages dev, and testing these restrictions do not apply.
      - name: Check tag compliance
        if: ${{ !steps.tag-check.outputs.has_matches && (matrix.environment != 'dev' && matrix.environment != 'testing') }}
        run: |
          echo "::warning title=Invalid deployment tag::In the future a deployment into ${{ matrix.environment }} using ${{ matrix.tag }} will be rejected."
